# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус продавца',
                'verbose_name_plural': 'Статусы продавца',
            },
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Status'),
        ),
    ]
