# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20171217_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
