# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20171217_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='goods',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
    ]
