# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-17 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_address_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='name',
            new_name='headline',
        ),
    ]
